data_info={
    'D_O':{
        'shape':'(day_len,num_stock)',
        'description':'当日开盘价'
    },
    'D_C':{
        'shape':'(day_len,num_stock)',
        'description':'当日收盘价'
    },
    'D_H':{
        'shape':'(day_len,num_stock)',
        'description':'当日最高价'
    },
    'D_L':{
        'shape':'(day_len,num_stock)',
        'description':'当日最低价'
    },
    'D_V':{
        'shape':'(day_len,num_stock)',
        'description':'当日成交额'
    },
    'M_O':{
        'shape':'(day_len,num_stock,minute_len)',
        'description':'日内每一分钟的开盘价'
    },
    'M_C':{
        'shape':'(day_len,num_stock,minute_len)',
        'description':'日内每一分钟的收盘价'
    },
    'M_H':{
        'shape':'(day_len,num_stock,minute_len)',
        'description':'日内每一分钟的最高价'
    },
    'M_L':{
        'shape':'(day_len,num_stock,minute_len)',
        'description':'日内每一分钟的最低价'
    },
    'M_V':{
        'shape':'(day_len,num_stock,minute_len)',
        'description':'日内每一分钟的成交额'
    },
}

op_info={
    'ts_pctchg':
        {'input_parameters':
            {
            'tensor':'shape=(day_len,num_stock),只允许输入这一个变量',
            },
        'output':
            {
            'tensor':'shape=(day_len,num_stock)',
            'description':'计算当日值相较于昨日值的涨跌幅,(tensor-tensor.shift(1))/tensor'
            },
    },
    'Mask_max':
        {'input_parameters':
            {
            'parameters1：tensor':'shape=(day_len,num_stock)',
            'parameters2：rolling_days':'int'
            },
        'output':
            {
            'output1：mask_tensor':'shape=(day_len,num_stock,rolling_days)',
            'description':'对于输入的tensor，用torch做unfold rolling_days，找到最大的1/5,将其标注为True，其余为False'
            },
    },
    'ts_mask_mean':
        {'input_parameters':
            {
                'parameters1：tensor':'shape=(day_len,num_stock)',
                'parameters2：mask':'shape=(day_len,num_stock,rolling_days)'
            },
        'output':
            {
            'output1:tensor':'shape=(day_len,num_stock)',
            'description':'先将tensor做unfold成和mask一样的shape，然后对于mask中为True的部分求平均'
            },
        }
}