data_info={
    'open':{
        'shape':'(day_len,num_stock)',
        'description':'当日开盘价'
    },
    'close':{
        'shape':'(day_len,num_stock)',
        'description':'当日收盘价'
    },
    'high':{
        'shape':'(day_len,num_stock)',
        'description':'当日最高价'
    },
    'low':{
        'shape':'(day_len,num_stock)',
        'description':'当日最低价'
    },
    'volume':{
        'shape':'(day_len,num_stock)',
        'description':'当日成交额'
    },
    'small':{
        'shape':'(day_len,num_stock)',
        'description':'当日散户成交额占所有成交额的比重'
    },
    'mid':{
        'shape':'(day_len,num_stock)',
        'description':'当日中户成交额占所有成交额的比重'
    },
    'big':{
        'shape':'(day_len,num_stock)',
        'description':'当日大户成交额占所有成交额的比重'
    },
    'superbig':{
        'shape':'(day_len,num_stock)',
        'description':'当日机构成交额占所有成交额的比重'
    },
}